### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by locks** [locks/ember-cli-typescript#3]
Hi,

I've noticed that this package doesn't seem to be maintained anymore.
Would you be willing to transfer it? I've been using TypeScript to develop my addons and I'd like to update the package to the latest versions of the different components.

Appreciated.

**Comment by flcdrg** [comment]
Sure, that would be great. I'll see how I can do that.

**Comment by flcdrg** [comment]
So I tried to transfer it to you, but it failed with this error "locks already has a repository in the kimroen/ember-cli-coffeescript network"

Let me know what you'd like to do.

**Comment by locks** [comment]
What about now? I sent a PR to another project that forked `ember-cli-coffeescript` but I've removed the repository.

**Comment by locks** [comment]
@flcdrg thank you, sir :smile: If you can also add me as an [npm owner](https://docs.npmjs.com/cli/owner) I'll coordinate publishing an update soon.

**Comment by flcdrg** [comment]
No worries!

That wasn't me that published to npm. I think you'll have to contact the person who published it up there. Hopefully they'll add you in seeing as you've taken over the repo.
